# Generated by Django 5.2.7 on 2025-10-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userextrafield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
